## Numpy
# Used for scientific computing
# provides support for arrays and matrices
# comes with a large collection of functions

In [27]:
import numpy as np

In [2]:
## 1d array

array=np.array([0,1,2,3,4])
print(array)
print(type(array))
array.shape

[0 1 2 3 4]
<class 'numpy.ndarray'>


(5,)

In [3]:
##2d array

array1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(array1)
print(type(array1))
array1.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>


(2, 5)

In [4]:
## Reshaping the array
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [5]:
## Getting all elements as unity
np.ones((2,3)) # important in deep learning

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
## Getting an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
## Attributes of Numpy array

array2=np.array([[0,1,2,3,4],[5,6,7,8,9]])

print("Array:\n",array2) # prints array
print("Dimensions;", array2.ndim) # prints dimensions
print("Shape:", array2.shape) # prints shape
print("Size(no. of elements):", array2.size) # prints the number of elements
print("Datatype:",array2.dtype) # prints int64 ( different for each platform) 
print("Size of item:", array.itemsize) # prints the size of item

Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Dimensions; 2
Shape: (2, 5)
Size(no. of elements): 10
Datatype: int64
Size of item: 8


In [8]:
## Numpy vectorized operation

array_1=np.array([1,2,3,4,5])
array_2=np.array([10,20,30,40,50])

## Addition
print("Addition:",array_1 + array_2)
## Subtraction
print("Subtraction:",array_1 - array_2)
## Multiplication
print("Multiplication:",array_1 * array_2)
## Division
print("Division:",array_1 / array_2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [9]:
## Universal Functions

array_3=np.array([1,2,3,4,5])

## Square root
print("Square root:", np.sqrt(array_3))
## Exponential
print("Exponential:",np.exp(array_3))
## Sine
print("Sine:",np.sin(array_3))
## Natural log
print("Natural log:",np.log(array_3))


Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
## Array Slicing and Indexing
Array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array:\n",Array)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(Array[1])
print(Array[1][2])

print(Array[1:,1:3])

[5 6 7 8]
7
[[ 6  7]
 [10 11]]


In [12]:
## Modify Array elements

print("Array:\n", Array)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
Array[0][2]=30
print(Array)

[[ 1  2 30  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
Array[1:]=20
print(Array)

[[ 1  2 30  4]
 [20 20 20 20]
 [20 20 20 20]]


In [9]:
## Statistical concepts
data_1=np.array([1,2,3,4,5,6])
## Mean
mean=np.mean(data_1)
print("Mean:", mean)
## Median
median=np.median(data_1)
print("Medain:",median)
## Standard Deviation
std_dev=np.std(data_1)
print("Standard Deviation:", std_dev)
## Variance
variance=np.var(data_1)
print("Variance:",variance)

Mean: 3.5
Medain: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665


In [ ]:
## Statistical concepts
## Normalization
## To have a mean of 0 and standard deviation of 1

data=([1,2,3,4,5,6,7,8])
mean=np.mean(data)
std_dev=np.std(data)
## Nomralization
Normalized_data=(data-mean)/std_dev
print("Normalized_data:\n", Normalized_data)

Normalized_data:
 [-1.52752523 -1.09108945 -0.65465367 -0.21821789  0.21821789  0.65465367
  1.09108945  1.52752523]


In [26]:
## Logcical Operations
data=np.array([1,2,3,4,5,6,7,8])

data[(data>=2) & (data<=8)]


array([2, 3, 4, 5, 6, 7, 8])

In [18]:
data=([1,2,3,4,5,6])
for i in data:
    if i % 2==0:
        print (i,"is even")
    else :
        print(i,"is odd")

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
